<?xml version="1.0" encoding="utf-8"?><Database Name="CharacterEvolution" Class="TextEvolutionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=CharacterEvolution;Integrated Security=True" SettingsObjectName="CharacterEvolution.Properties.Settings" SettingsPropertyName="CharacterEvolutionConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.GameImage" Member="GameImage">
    <Type Name="GameImage">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="littleImage" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.TextEvolution" Member="TextEvolution">
    <Type Name="TextEvolution">
      <Column Name="SID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Character" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MinImage" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MaxImage" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
</Database>